### PR TITLE
move application route to dummy

### LINKED ISSUE #1854: Inconsistent builds with ember-cli-typescript
Ref: https://github.com/typed-ember/ember-cli-typescript/issues/724

inputs:

typescripted app with application route:
`/app/routes/application.ts`
ember-simple-auth addon installed

addon expose to app namespace  `ember-simple-auth/app/routes/application.js` file.

sometimes (1/10) `/app/routes/application.ts` rewritten by `ember-simple-auth/app/routes/application.js` and this is may produce tricky to debug errors.

how to fix?

have files with `.js` on both sides (`/app/routes/application.ts` -> `/app/routes/application.js`)

why this issue?
- to give developers more inputs about existing problem and add motivation to fix ember internals about merging files with different extensions

### LINKED ISSUE #2279: Default application route breaks embroider
Removing the default route here would fix that, see issue in embroider https://github.com/embroider-build/embroider/issues/675 for context.

### PR DESCRIPTION
**Pull request by BobrImperator**
ESA main package doesn't have any need for application route.
This PR moves application route to the dummy app which needs it for testing, but doesn't have to ship it to user apps.

- Move application route to dummy

Should close #1854, and close #2279

### CODE REVIEW

**Comment by marcoow** [comment]
I think we need the application route to exist for [this initializer](https://github.com/simplabs/ember-simple-auth/blob/master/packages/ember-simple-auth/addon/initializers/setup-session-restoration.js) to work. Try removing it and the dummy app should fail.

That said, it should be possible I think to get the application's `application` route without the file being present (we should simply receive the route instance that Ember generates on-the-fly in that case) but I'm not sure why that's not being done currently – maybe wasn't possible with an earlier version of Ember?

**Comment by BobrImperator** [comment]
@marcoow I know that Application route is needed for the initializer, but it doesn't have to exist in ember-simple-auth addon, but only in the dummy that is the 'real' app that uses the addon.

Basically meaning that user apps have their application routes defined already.

**Comment by marcoow** [comment]
Yes but we don't want people to have to create the file in their apps for ESA to work since that's a major footgun.

**Comment by BobrImperator** [comment]
Apps *must* have an application route, be it `application.js` or `application.hbs` where for the latter there's an implicit js class created, or am I wrong here?

**Comment by marcoow** [comment]
You don't have to have the `app/routes/application.js` file.

**Comment by BobrImperator** [comment]
closed in favor of #2307

**Pull request closed without merging**
