### PR TITLE
Fix dummy app authorizers filename

### PR DESCRIPTION
**Pull request by anilmaurya**
Authorizer filename should be oauth2 instead application

### CODE REVIEW

**Comment by marcoow** [comment]
`app/authorizers/application.js` is fine

**Comment by anilmaurya** [comment]
@marcoow It was not working for me, changing to oauth2.js fixed it. 

In Readme also, its mentioned to add app/authorizers/oauth2.js .

**Comment by marcoow** [comment]
You just have to use the name name you use when calling the session service's `authorize` method or you set the `DataAdapterMixin`'s `authorizer` property to.

Also this change breaks the build.

**Comment by anilmaurya** [comment]
Ok , I didn't knew that. Thanks for the info.

**Pull request closed without merging**
