### PR TITLE
Add instanceInitializer

### PR DESCRIPTION
**Pull request by quaertym**
This PR is to pave the way for fixing https://github.com/simplabs/ember-simple-auth/issues/517. I think it is logical to split the fix into multiple commits.

### CODE REVIEW

**Comment by OpakAlex** [comment]
+1

**Comment by quaertym** [comment]
@marcoow Any comment on this?

**Comment by marcoow** [comment]
This would also need to make sure that the existing initializer doesn't use the container's `lookup` method when that's done in the instance initializer, otherwise you'd still get the deprecation notice. Also there's #532 which takes some more steps to solve the problem which I'm not sure are all actually necessary.

**Comment by listepo** [comment]
+1

**Comment by rafaelmezzomo** [comment]
+1

**Comment by marcoow** [comment]
See https://github.com/simplabs/ember-simple-auth/pull/532#issuecomment-113643062 - would be cool to get something like this for the [`ember-cli-addon` branch](https://github.com/simplabs/ember-simple-auth/pull/532#issuecomment-113643062).

**Comment by marcoow** [comment]
see #564, thanks for the effort!

**Pull request closed without merging**
