### PR TITLE
Make Ember Simple Auth an Ember CLI addon only (ESA 1.0)

### PR DESCRIPTION
**Pull request by marcoow**
see #519 

This will be the 1.0 release of Ember Simple Auth, turning the library into a first class Ember CLI addon and removing the bower and globals distributions. The 1.0 version will of course also support Ember 2.0.

- [x] turn the session into a service (actually there's a service now that wraps the session which itself isn't directly exposed anymore)
- [x] split the initialization code into initializers and instance initializers
- [ ] make sure the documentation is correctly generated and convert all examples and references to Ember CLI/ES6 modules syntax
- [ ] move the setup of `$.ajaxPrefilter` into a dedicated initializer that can optionally be loaded (there should probably also be an initializer that e.g. sets up authorization on the Ember Data adapter instead). The current method of automatically loading it should be extracted into an addon so it's easy to upgrade projects in a non-breaking way.
- [ ] fix tests (currently fail in beta and canary because of switchfly/ember-mocha#48)

~~- [ ] rename `Authenticator.restore` to `Authenticator.validate`~~ (don't think this is actually a good idea)

### CODE REVIEW

**Comment by fsmanuel** [comment]
@marcoow How can I help to push things forward?

**Comment by marcoow** [comment]
@fsmanuel: maybe you could have a look at the documentation generation? See the `grunt docs` task on the master branch - that would basically have to be ported to Broccoli.

**Comment by quaertym** [comment]
@marcoow Is this usable now?

**Comment by marcoow** [comment]
@quaertym: this isn't ready yet

**Comment by abradner** [comment]
I'm excited, this looks close! need any extra manpower anywhere?

**Comment by marcoow** [comment]
@abradner: yeah, should hopefully be ready soon. I would really appreciate if someone would come up with a good proposal to tackle #270 as if that's ever done it should be done before the 1.0 release as it would most likely result in a breaking change…

**Comment by harianus** [comment]
What is the estimated time for this? We want to integrate this soon!

**Comment by marcoow** [comment]
first beta will be released next week latest

**Comment by fotinakis** [comment]
Excited to see that this is in progress, just upgraded to Ember 1.13.1 and this is the last remaining piece for me to finish. Let me know if I can help beta test.

**Comment by justinph** [comment]
I'm looking forward to this as well. Will be happy to help beta test when available. Thanks for the hard work on it, @marcoow.

**Comment by marcoow** [comment]
see follow-up pull request #602

**Pull request closed without merging**
