### PR TITLE
Fix DeviseAuthorizer path on README's 'Customizing an Authorizer' session

### PR DESCRIPTION
**Pull request by romulomachado**

### CODE REVIEW

**Comment by marcoow** [comment]
The build is failing for this. Can you rebase on the latest master?

**Comment by romulomachado** [comment]
There you go! I've done that earlier today, but forgot to push the updated master. :grimacing:

**Comment by romulomachado** [comment]
Everything green now! :smile:

**Comment by marcoow** [comment]
👍

**Pull request merged**
