### PR TITLE
add section about an authorizer to the readme

### PR DESCRIPTION
**Pull request by albertjan**
as talked about in #452

### CODE REVIEW

**Comment by marcoow** [comment]
I think the section you're adding is a little misleading. Authenticators and authorizers are somewhat bound together as the authorizer depends on data acquired by the authenticator. That's why e.g. the OAuth 2.0 authorizer doesn't work (while actually it might work but that would be coincidence) when using a torii authenticator as that acquires different data than the OAuth 2.0 authorizer expects.

Also, for torii that's especially difficult as even the torii authenticator doesn't know which data is acquired as that's specific for the actual torii provider it uses.

Third, the authorization mechanism your app uses isn't necessarily bound to the authentication mechanism (which could actually be many). So maybe you support Facebook, Google and Twitter authentication via torii and use your own authorization header that you inject into requests, meaning there is no one _"correct"_ torii authorizer.

So instead of adding the suggested session, I'd add sth, that simply says that there is no authorizer in the torii extension library but you need to implement your own depending on your authorization mechanism and that that authorizer must be able to handle the different types of authentication data the torii providers you're using acquire.

**Comment by albertjan** [comment]
Ok I'll remove the example authorizer. And explain a bit more that there is no one implementation that will fit all use cases.

**Comment by marcoow** [comment]
Hm, I'm not actually sure anymore that what you're describing (using e.g. the FB or Google token as a Bearer` token against one's API) is actually a use case of this extension library. Actually I would always extend the torii authenticator and post the authentication data to my own API to validate it and exchange it against a `Bearer` token that my own API maintains and then use that to authorize API requests.

**Comment by albertjan** [comment]
@marcoow ah yes offcourse. We're using openid connect so we don't have the extra validation step. Should I close this PR?  Or should I add some more documentation about the rest of the auth flow. 

The point is I was really happy with the simple-auth torii integration but it took me a while to find out there were some parts missing, including the authorizer. So for openid connect the only thing you have to do is add a authorizer. But since openid connect hasn't really landed yet, this addition to the documentation seems a bit weird esp. from a normal oauth2 perspective. 

[This](https://github.com/Vestorly/torii/issues/148) is another piece of the puzzle that isn't implemented by default. I would probably be part of your extension of the torii provider.

**Comment by marcoow** [comment]
Yes, correct `fetch` implementation is kind of lacking in torii still.

Can you maybe change the PR so that it says that the torii package is basically only a starting point for custom solutions as it cannot define an authorizer as it's unknown which exact torii providers will be used?

Sorry - I appreciate the effort, I'm just worried people might get lead in the wrong direction.

**Comment by albertjan** [comment]
@marcoow Yeah sure I'll change it. And try to explain it a bit better. I don't mind, people should definitely not be led in the wrong direction :smile: no direction would be better in that case.

**Comment by albertjan** [comment]
I've updated it added a hint to finishing the oauth flow and the `fetch` function. When new users get this far implementing their own authorizer will be a piece of cake :smile:

**Pull request merged**
