### PR TITLE
ci(renovate): use renovate's json5 preset

### PR DESCRIPTION
**Pull request by oscard0m**

### CODE REVIEW

**Review by marcoow — APPROVED** [review]

**Comment by oscard0m** [comment]
Any clue on the CI checks failing?

**Comment by oscard0m** [comment]
> Any clue why the CI checks are failing? @marcoow
> 
> I noticed things stopped working after this: #2397

Just a follow up on this comment @marcoow

**Comment by marcoow** [comment]
I don't know what caused this

**Comment by BobrImperator** [comment]
Closing in favor of #2435

**Pull request closed without merging**
