### PR TITLE
Typo in docs comment for headersForRequest

### PR DESCRIPTION
**Pull request by olleolleolle**
This PR fixes a docs typo, completing the Mixin's method list.

### CODE REVIEW

**Comment by marcoow** [comment]
Awesome, thanks! Just in time for 1.2-beta.1

**Comment by olleolleolle** [comment]
@marcoow Oooh, I have an upcoming feature, too.

At my job, we built a DeviseTokenAuth authorizer/authenticator. And we want to offer it as a PR.

**Comment by marcoow** [comment]
Cool. How is that different from the existing Devise authenticator/authorizer?

**Comment by olleolleolle** [comment]
Oh, it's using tokens.

The docs in [ember-simple-auth](http://ember-simple-auth.com/api/classes/DeviseAuthenticator.html) have a gist from 2013 to point out that Devise no longer does token-style auth.

**Comment by olleolleolle** [comment]
Sorry (I was answering the wrong question). I'll make a PR.

**Pull request merged**
