### PR TITLE
Fastboot Feature Branch

### PR DESCRIPTION
**Pull request by arjansingh**
@marcoow, what's the base for `fastboot`? I rebased off master last night so my code should be mergeable. (See #1031)

### CODE REVIEW

**Comment by marcoow** [comment]
@arjansingh: rebase on the `fastboot` branch instead. That's based on your branch iirc with a few fixes.

**Comment by josemarluedke** [comment]
@marcoow since this is rebased now, can we merge this? My hope is to start working again on this tonight so it would be good to have this merged.

**Comment by arjansingh** [comment]
The current build failure looks like a caching issue to me.

**Comment by josemarluedke** [comment]
@arjansingh that issue is actually because of ember-cli-fastboot beta 5. (https://github.com/ember-fastboot/ember-cli-fastboot/pull/228)

Can you bump to beta 7?

**Comment by arjansingh** [comment]
easy peasy

**Comment by josemarluedke** [comment]
The tests failures now are actually failures. Most likely rebase problems.

**Comment by josemarluedke** [comment]
Got the tests passing with this commit: https://github.com/simplabs/ember-simple-auth/commit/2e2506bee93223d7e9bc98b2a5d3be147a3916c5

I can get a PR open after this is merged, or it can be cherry-picked here.

**Comment by arjansingh** [comment]
I vote merge and then follow up with your pr... The whole point of this
branch is that we can be loose with process since it doesn't affect the
mainline.

>

-- 
Arjan

**Comment by marcoow** [comment]
awesome - merging 🎉

**Pull request merged**
