### PR TITLE
Clean up Node.js/fastboot tests

### PR DESCRIPTION
**Pull request by Turbo87**

### CODE REVIEW

**Comment by marcoow** [comment]
Where the dir names of the fastboot fixture apps switched?

**Comment by Turbo87** [comment]
> Where the dir names of the fastboot fixture apps switched?

not sure what you mean, but I did not switch any folder names

**Comment by marcoow** [comment]
e.g. `fixtures/not-fastboot-ready-app/app/app.js` is now `fixtures/fastboot-ready-app/app/app.js`:

bildschirmfoto 2017-02-09 um 12 47 18

**Comment by Turbo87** [comment]
seems like git detected something strange there. I guess the files are identical and so it didn't know which got moved into which location.

**Comment by marcoow** [comment]
make sense

**Pull request merged**
