### PR TITLE
Re-enable FastBoot tests

### LINKED ISSUE #1719: Re-enable *mandatory* fastboot tests in CI
The fastboot CI job has been failing on master for about a month, probably due to a combination of

- ember-data#master being incompatible with recent releases of ember (you'll get a rollup build error when attempting to build)
- ember-fetch's custom rollup stuff not working nicely with fastboot testing infrastructure

To address this, I've improved our CI configuration (#1718) to detect this kind of breakage in nightly builds, by ensuring that tests are run both _with and without_ taking the lockfile into account.

Unfortunately, getting fastboot testing passing again will take some non-trivial digging. Here's what I've found in my limited time
- in https://github.com/kaliber5/ember-fastboot-addon-tests most dependency versions are "borrowed" from the library being tested. ember-data is an exception, which defaults to `ember-data#master`. I've opened a PR here which at least gets the first test running again https://github.com/kaliber5/ember-fastboot-addon-tests/pull/26
- ember-fetch's custom rollup stuff seems to be failing when it fails to find (I think) babel-preset-env in the fastboot test app. I haven't had a chance to dig into this any further yet

In the mean time, to allow meaningful development to continue while some of this infrastructure is updated/repaired, I've marked the CI job as an allowed failure.

### PR DESCRIPTION
**Pull request by marcoow**
This re-enables the FastBoot tests using ember-cli-fastboot-testing. It also moves the FastBoot tests into the new `test-app`. It removes some of the old tests that didn't really make sense anyway – we had special routes in the app to trigger certain functionality and I think we should never have done that in the first place and definitely not port these tests over now.

closes #1719

### CODE REVIEW

**Comment by marcoow** [comment]
Hm, not sure why the tests are failing – seems like something is wrong with the test that passes an authenticated session manually in the cookie: https://github.com/simplabs/ember-simple-auth/pull/2209/files#diff-4507cbd2f9d136062847ed8f9547b662R19

**Comment by sdebarros** [comment]
@marcoow I updated the test, it was failing because some API calls where not mocked and the error would cause the session to be invalidated. Now they failed with this error:
```
Error while processing route: protected najax does not seem to be defined in your app. Did you override it via `addOrOverrideSandboxGlobals` in the fastboot server?
```

I finally figured out why it happens, we are using ember-cli-fastboot-testing v0.4.0, which has fastboot 3 as a dependency, and fastboot 3 doesn't include `najax` as a global anymore, so we either have to set the global in a config (see https://embermap.github.io/ember-cli-fastboot-testing/docs/fastboot-configuration) (and maybe also update our fastboot dependencies to v3?) or use v0.3.0 of ember-cli-fastboot-testing.

**Comment by marcoow** [comment]
@sdebarros great 🎉 The FastBoot tests have been disabled for some time so the dependencies are most likely horribly outdated, yeah. Feel free to upgrade everything as necessary – it's all just `devDependencies` anyway…

**Comment by marcoow** [comment]
Ah, nevermind – I had removed the outdated dependencies already of course 🤦 But upgrading to the latest ember-cli-fastboot-testing and configuring `najax` as a global seems good. Can you push that?

**Comment by sdebarros** [comment]
@marcoow done, tests are passing now 🎉

**Comment by marcoow** [comment]
Awesome – last step missing is only to re-enable them to run in CI 🎉

**Comment by marcoow** [comment]
@sdebarros nevermind me again, I guess I'm already in vacation mode – of course the tests run as part of `ember test`…

**Pull request merged**
