### PR TITLE
Pass session data to torii close method

### PR DESCRIPTION
**Pull request by steven-ferguson**
Retargeting https://github.com/simplabs/ember-simple-auth/pull/583 to the ```ember-cli-addon``` branch.

### CODE REVIEW

**Comment by marcoow** [comment]
Adding a test for that would be great!

**Comment by marcoow** [comment]
@steven-ferguson: would like to merge that - would have to have a test though…

**Comment by steven-ferguson** [comment]
@marcoow Test added.

**Comment by marcoow** [comment]
Hm, tests fail now - don't think that's caused by your changes though but probably by changes in the latest Ember beta. Will check later…

**Pull request closed without merging**
