### PR TITLE
Added names to mixins for Ember Inspector

### LINKED ISSUE #1357: Feature: Name mixins and other exports of this addon
I work on large projects and more than often I find myself wading through a whole bunch of `UnknownMixin` and similar objects inside of Ember Inspector. 

We recently discovered that Ember Inspector reads the `[Ember.NAME_KEY]` property of each Ember Object to display a proper name.

Therefore I propose to add this property to all mixins and objects exported by this addon, making the object stack a bit easier to read. 

If this sounds interesting, I'll supply a pull request for this. 🙂

### PR DESCRIPTION
**Pull request by pichfl**
Do not merge this yet, tests are missing.

Closes #1357

### CODE REVIEW

**Comment by marcoow** [comment]
You'll need to rebase on the latest `master` to fix the build.

**Comment by pichfl** [comment]
I'll clean this up and provide tests as soonish, I just wanted to file the PR and close the ticket. Please don't merge this until I figured out how I can test this 😄

**Comment by Turbo87** [comment]
@pichfl I don't think there is currently a reasonable way to test this. I'd suggest to rebase the branch and remove the unrelated changes and IMHO then we can merge this.

**Comment by pichfl** [comment]
Alright, rebase incoming.

**Comment by pichfl** [comment]
Should be ready to merge now @Turbo87

**Comment by Turbo87** [comment]
@pichfl looks like you need to add back the `import Ember from 'ember'` lines that were removed in https://github.com/simplabs/ember-simple-auth/pull/1411. Unfortunately `NAME_KEY` is not exported by the New Module Imports yet.

**Comment by pichfl** [comment]
Oh your right. I wonder if it ever will be.

**Comment by pichfl** [comment]
Hrrrm, I'm not sure I actually want to do this. 

Digging through the mixin source code I found Ember actually imports this from `ember-utils`. Do you think this could work as well here? `import { NAME_KEY } from 'ember-utils';`

**Comment by Turbo87** [comment]
`ember-utils` is deprecated, don't use it!

**Comment by pichfl** [comment]
I just pushed a fix, but now I'm unsure if we should actually merge this. While it makes the output in the Inspector easier, it will also interfere with tree shaking. I suppose I need to file a bug report for exposing the `NAME_KEY` symbol somewhere, I just don't know which repo would be the right one right now.

**Comment by Turbo87** [comment]
> I suppose I need to file a bug report for exposing the NAME_KEY symbol somewhere, I just don't know which repo would be the right one right now.

already did that a couple of hours ago in https://github.com/ember-cli/ember-rfc176-data 😉

**Comment by pichfl** [comment]
I bow to you sir

**Comment by marcoow** [comment]
@pichfl: should this be closed (see https://github.com/ember-cli/ember-rfc176-data/issues/12#issuecomment-320232883)?

**Pull request closed without merging**
