### PR TITLE
Pass xhr settings to authorizer.

### PR DESCRIPTION
**Pull request by patrickfournier**
In response to issue #862 and for my own similar needs, I added a parameter to SessionService.authorize() to permit access to the XHR settings.

### CODE REVIEW

**Comment by marcoow** [comment]
The authorizer can authorize any code block really and has no knowledge of XHR. If you're not using the `DataAdapterMixin` you'd be using it through the session sth. like this:

```js
this.get('session').authorize('authorizer:some', (headerName, headerValue) => {
  xhr.setRequestHeader(headerName, headerValue);
});
```

so no need to pass XHR options.

**Comment by patrickfournier** [comment]
From what you say, I understand that DataAdapterMixin is tied in a certain way to the authorizer. So if my authorizer needs to access the xhr settings, I would need to write a new data adapter mixin with a different `beforeSend`, something like this:

  ajaxOptions() {
    const authorizer = this.get('authorizer');
    Ember.assert("You're using the DataAdapterMixin without specifying an authorizer. Please add `authorizer: 'authorizer:application'` to your adapter.", Ember.isPresent(authorizer));

    let hash = this._super(...arguments);
    let { beforeSend } = hash;

    hash.beforeSend = (xhr, settings) => {
      this.get('session').authorize(authorizer, (publicKey, secretKey) => {
        var stringToSign = extractDataFromXHRSettings(settings);
        var signature = HMAC_SHA256(stringToSign, secretKey);
        xhr.setRequestHeader('Authorization', Credential=' + publicKey + ',Signature=' + signature);
      }, settings);
      if (beforeSend) {
        beforeSend(xhr, settings);
      }
    };
    return hash;
  },

**Comment by marcoow** [comment]
Authorizers just authorize a block (which doesn't necessarily issue an XHR request) of code by converting the session data that was acquired by the authenticator when it authenticated the session to some other data, e.g. a header name and value. If you need to convert that data further you'd have to do so in the block that the session's `authorize` method calls with the authorization data - so yes, you'd have to define your own DataAdapterMixin like above.

**Comment by patrickfournier** [comment]
Thanks for the confirmation!

**Comment by marcoow** [comment]
This will actually be added via #870

**Comment by marcoow** [comment]
oops

**Pull request closed without merging**
