### PR TITLE
Add link to fastboot demo on ember-simple-auth.com

### PR DESCRIPTION
**Pull request by stevenwu**
A part of #1389

### CODE REVIEW

**Comment by stevenwu** [comment]
Are we on a paid plan? The instances are going to sleep. Other than that, everything works.

**Comment by marcoow** [comment]
Yes, we are on a paid plan actually. Are instances not supposed to go to sleep on paid plans? I suppose not but can't find anything about instances going to sleep at all in the features list on now.sh.

**Comment by marcoow** [comment]
@stevenwu: can you enable edits from maintainers on this PR?

**Comment by stevenwu** [comment]
@marcoow I disabled and reenabled it. Does it work now?

**Comment by marcoow** [comment]
Hm, I think something got messed up on my site - see #1486 which replaces this.

**Pull request closed without merging**
