### PR TITLE
Fix oauth2 authenticate data object

### PR DESCRIPTION
**Pull request by dustinfarris**
I think this was typoed in https://github.com/simplabs/ember-simple-auth/commit/300edb530bdc3dee836c13e186c962b018a03681#diff-931dc51edd167948e773858f72a47233L137

### CODE REVIEW

**Comment by dustinfarris** [comment]
Actually this isn't quite right yet.. one more commit coming.

**Comment by dustinfarris** [comment]
Actually skip this.  Need to know whether authenticate should accept and object as in the examples, or 2 args as in the implementation.  Either way it needs to be fixed.

**Comment by pichfl** [comment]
@dustinfarris You might want to read this, though: https://babeljs.io/docs/learn-es2015/#enhanced-object-literals

**Comment by dustinfarris** [comment]
@pichfl this was causing problems with authentication where the ajax call was POSTING

```
username[identification]: "myusername",
username[password]: undefined
```

maybe my fix isn't right, but this is definitely broken.

**Comment by dustinfarris** [comment]
@pichfl ok i see what you're saying.  so this wasn't a typo after all.

i think the conflict of passing an object vs 2 args is still a problem though.

**Pull request closed without merging**
