### PR TITLE
Update `.npmignore` file

### PR DESCRIPTION
**Pull request by Turbo87**
This changes the "unpacked size" of the package from 2.2 MB to 194.9 kB

### CODE REVIEW

**Comment by Turbo87** [comment]
@locks I totally agree, except: https://github.com/npm/npm/issues/5673

**Comment by Turbo87** [comment]
@marcoow I don't understand, can you elaborate how that is relevant for the `.npmignore` file? are you confusing this with `.gitignore`?

**Comment by marcoow** [comment]
There's https://github.com/simplabs/ember-simple-auth/issues/1339#issuecomment-306852493 for example - I really don't remember all of the details and would have to dig through the issue history…

**Comment by marcoow** [comment]
also see #1482

**Comment by Turbo87** [comment]
😩

**Pull request closed without merging**
