### PR TITLE
devise authenticator now also processing the JSON API data.

### PR DESCRIPTION
**Pull request by texpert**

### CODE REVIEW

**Comment by marcoow** [comment]
Thanks for your effort but I don't think JSON API should be supported with the devise adapter. JSON API is a resource based format and I don't think is a great fit for authentication. This could certainly live on in an addon to ember-simple-auth of course that people could use that actually require JSON API for auth requests on the backend.

In that case I'd suggest to extend the `Devise` authenticator though so you don't have to keep your version of the base authenticator up to date in the addon.

**Comment by marcoow** [comment]
also see my comment on the topic here: https://github.com/simplabs/ember-simple-auth/issues/1128#issuecomment-266970372

**Comment by texpert** [comment]
As you wish, of course, @marcoow , but just to mention that a common enough use case for authorizing a resource based API is using Devise authenticator + Doorkeeper authorizer.

**Comment by marcoow** [comment]
Sure but I think what you should do is use resource-focussed endpoints and JSON API for managing resources and sth. else for authentication/unauthentication requests. In the end, there is no resource you're creating when authenticating - there's no model neither on the client or server side etc.

Both JSON API and Devise/Doorkeeper can coexist in an app perfectly fine - I would just not use JSON API for the auth requests.

**Comment by bravo-kernel** [comment]
For future reference by people looking into this... in all honesty using JSON API for authentication is perfectly fine considering one is basically creating a new (jwt) token (resource) when authenticating. Add to that the benefits of DRY use of shared application logic for validation, errors, etc and it is actually a pretty sane choice.

However... as much as I stand for the above I gave up and made the exception as well, no JSON API for auth ;)

**Pull request closed without merging**
