### PR TITLE
Remove unnecessary calls to off() that trigger deprecation warnings

### PR DESCRIPTION
**Pull request by richard-viney**
Followup to #1722.

### CODE REVIEW

**Comment by Turbo87** [comment]
why do you think that these are unnecessary? wouldn't it lead to memory-leaks if we removed them?

**Comment by richard-viney** [comment]
Believe it's ok because the original code was immediately putting the event handlers back on after just removing them.

I tested that multiple calls to `on()` with identical arguments doesn't result in the specified function being called multiple times, i.e. it doesn't allow the same `[context, function]` pair to be registered more than once. That means that the `off()` calls removed in this PR weren't ever doing much anyway.

Thoughts?

**Comment by josemarluedke** [comment]
@marcoow @Turbo87 @jessica-jordan Can we get a release containing this change? Thanks.

**Comment by robclancy** [comment]
Someone press the release button...

**Comment by jessica-jordan** [comment]
@josemarluedke @robclancy I'm on it!

**Comment by quaertym** [comment]
@jessica-jordan Please push to npm.

**Pull request merged**
