### PR TITLE
use url encoded  instead of setting a header

### PR DESCRIPTION
**Pull request by timini**
from https://aaronparecki.com/2012/07/29/2/oauth2-simplified

`
POST https://api.oauth2server.com/token
    grant_type=password&
    username=USERNAME&
    password=PASSWORD&
    client_id=CLIENT_ID
`

maybe related to #226

### CODE REVIEW

**Comment by marcoow** [comment]
Is this part of RFC 6749? If so this could be opt-in but the default of sending it in the `Authorization` header cannot be changed of course as that would break all apps out there using the OAuth 2 password authenticator.

**Comment by timini** [comment]
Yep

https://tools.ietf.org/html/rfc6749#section-2.3.1

```
Alternatively, the authorization server MAY support including the
   client credentials in the request-body using the following
   parameters:

   client_id
         REQUIRED.  The client identifier issued to the client during
         the registration process described by Section 2.2.

   client_secret
         REQUIRED.  The client secret.  The client MAY omit the
         parameter if the client secret is an empty string.
```

**Comment by timini** [comment]
I was using https://github.com/evonove/django-oauth-toolkit a popular oauth library, and this is the way it is implemented there.

**Comment by marcoow** [comment]
OK, seems good then. That should be opt-on though so the default behavior doesn't change in the authenticator. I think introducing a new property `sendClientIdInRequestBody` which defaults to `false` would be the way to go.

**Comment by timini** [comment]
Yep, that seems like a good way to go. Ill give it a go.

**Comment by tylerneu** [comment]
I too am using Django OAuth Toolkit and would like to see this change made. I'll work around it until then.

**Comment by marcoow** [comment]
@timini: any updates on this? Would be great to get this in.

**Comment by marcoow** [comment]
superseded by #1165

**Pull request closed without merging**
