### PR TITLE
Fix OAuth2 authenticator tokenRefreshOffset

### PR DESCRIPTION
**Pull request by sagaban**
Just a minor fix on how a random number is generated.

### CODE REVIEW

**Comment by marcoow** [comment]
Hm, was this actually broken before? Also this change breaks the build.

**Comment by sagaban** [comment]
Sorry, it was a rookie mistake

**Comment by marcoow** [comment]
I'm still not sure this was actually broken before - can you elaborate what this fixes?

**Comment by sagaban** [comment]
Sure: As I understand the method, `tokenRefreshOffset` should return a value between the min and the max defined values. Am I right? With the previous code it was not that way. It was working properly just because `min` was equal to `max - min`.

**Comment by marcoow** [comment]
hm: 
bildschirmfoto 2016-11-25 um 12 56 02

**Comment by sagaban** [comment]
Yes, with 10 and 5 will work, but with different values won't.
image

**Pull request merged**
