### PR TITLE
Add yuidoc generation to brocfile

### PR DESCRIPTION
**Pull request by fsmanuel**
Don't merge. We need to wait for ember-cli-yuidoc to make the options available (https://github.com/cibernox/ember-cli-yuidoc/issues/21).

Generate the docs: `npm run docs`

### CODE REVIEW

**Comment by marcoow** [comment]
Thanks for the effort - I can tell these doc tasks are usually a pain ;) We'd also need to figure out how we actually want to document classes etc. as the class names that are used now (`SimpleAuth.Session` etc.) won't exist anymore in the future…

**Comment by fsmanuel** [comment]
Oh yeah it was a pain.
We have to watch out for the new filename as well it's now `dist/docs/index.html` and i wonder how you treat the other packages (ember-cli-simple-auth-torii, etc.). They are all bundled in this addon, right?

**Comment by marcoow** [comment]
Yes, there will also be one single bundle and only one API docs HTML.

**Comment by fsmanuel** [comment]
What do you mean by "how we actually want to document classes"? As i see it, we should remove the `@namespace` and the box with "Standard AMD".

**Comment by marcoow** [comment]
Right, that's what I meant. Just removing the `@namespace`s makes sense of course - guess I was just thinking too complicated…

**Comment by fsmanuel** [comment]
There is an inconsistency with the imports in the examples and the ES6 import statements:
Examples: `ember-simple-auth/`
ES6: `simple-auth/`

**Comment by marcoow** [comment]
`ember-simple-auth` will be the namespace for all the modules.

**Comment by fsmanuel** [comment]
I'll open a new PR that uses `ember-simple-auth` and removes the `@namespace`

**Comment by marcoow** [comment]
Should be fine to do everything in this I'd say.

**Comment by fsmanuel** [comment]
What about the namespace of `Authenticators`, `Authorizers`, etc. Should they still exist?

**Comment by marcoow** [comment]
The authenticators, authorizers and stores will be merged directly into the host application (see e.g. https://github.com/simplabs/ember-simple-auth/tree/ember-cli-addon/app/authenticators) and so shouldn't have a namespace as they'll actually be available under the app's own namespace.

**Comment by fsmanuel** [comment]
got it!

**Comment by fsmanuel** [comment]
Travis fails because of a timeout...

**Comment by marcoow** [comment]
restarted the build manually…

**Comment by fsmanuel** [comment]
@marcoow ready to merge.

**Comment by marcoow** [comment]
@fsmanuel: how do I actually build the docs (I though `ember docs`)?

**Comment by marcoow** [comment]
@fsmanuel: what's the command to run the docs generation?

**Comment by fsmanuel** [comment]
@marcoow `npm run docs`

**Comment by marcoow** [comment]
Ah, I see - thanks. Wouldn't it be nice to have a custom task like `ember docs`? Not sure whether that would be feasible though…

**Comment by fsmanuel** [comment]
I will have a look at the ember commands and how `ember-cli-yuidoc` implements the `ember g ember-cli-yuidoc` command. I guess it should be easy to add `ember docs` that is an alias for `ember build --docs -e docs`. What I'm not sure about is if we expose that command to the host app...

**Comment by marcoow** [comment]
It doesn't really seem clean to me to have a dedicated environment for docs. Is that actually necessary when there's a custom command instead?

**Comment by fsmanuel** [comment]
I don't like the idea of a custom command because it would be exposed in every app that uses ember-simple auth and would probably fail in all that apps if invoked.
I used the environment to not generate docs on every build (e.g. Travis tests). I switched that to the way ember-cli-yuidocs does it [Code](https://github.com/cibernox/ember-cli-yuidoc/blob/master/index.js#L19).

**Comment by marcoow** [comment]
OK, I see. The above was really more an unfiltered stream of thoughts I had about the topic - don't actually know much about custom tasks etc. in ember cli.

**Pull request merged**
