### PR TITLE
Revert "Fix ember 2.x compatibility"

### PR DESCRIPTION
**Pull request by quaertym**
Reverts simplabs/ember-simple-auth#636

### CODE REVIEW

**Comment by marcoow** [comment]
Keeping that open until docs have been added as well - no need to add that here though as the complete docs have to be rewritten anyway. I'd say there should be a warning though when the torii authenticator is used but torii is not installed.

**Comment by quaertym** [comment]
I agree. So merge this?

**Comment by marcoow** [comment]
Can you add an `Ember.Logger.warn` whenever the torii authenticator is used but torii isn't installed? That should probably go into the torii authenticator's `restore` and `authenticate` methods.

**Comment by quaertym** [comment]
Closed in favor of  https://github.com/simplabs/ember-simple-auth/pull/674

**Pull request closed without merging**
