### PR TITLE
Fix deprecations related to `deprecate` util

### PR DESCRIPTION
**Pull request by bertdeblock**
Fixes the new deprecations introduced in #2318.

### CODE REVIEW

**Review by BobrImperator — APPROVED** [review]
Thanks for this :)

**Review by snewcomer — APPROVED** [review]

**Comment by lougreenwood** [comment]
Can we get this or one of the other 2 PRs which fix this merged please?

https://github.com/simplabs/ember-simple-auth/pull/2335
https://github.com/simplabs/ember-simple-auth/pull/2347

**Comment by BobrImperator** [comment]
Sorry for the delay on this 🥲 

@bertdeblock do you think we still need the changes?
Is there any advantage to having the `since.available` property defined?

**Comment by bertdeblock** [comment]
TBH, I'm not _super_ familiar with the deprecation staging RFC and how it should be applied within addons. I'm guessing the deprecation warnings are gone now?

**Comment by BobrImperator** [comment]
I think they are, and probably the available property is not needed anymore.
Should we close this?

**Pull request closed without merging**
